- name: DEV debug test vars
  debug:
    msg: "Dev os_subnet_range is {{ os_subnet_range }}"

- name: Create working directory
  tempfile:
    state: directory
  register: ocp_tmp
  when: ocp_tmp is not defined or ocp_tmp == ''

- name: Template openshift-install file in {{ ocp_tmp.path }}
  template:
    src: dev/install-config.j2
    dest: "{{ ocp_tmp.path }}/install-config.yaml"

- name: Execute openshift-install
  command:
    cmd: "{{ cli_base_dir }}/openshift-install create cluster --dir={{ ocp_tmp.path }}"
    