---
- debug:
    msg: "{{ lookup('env', 'HOME') }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/clis"
    state: directory
    mode: '0755'

- name: 'Download the OpenShift client'
  get_url:
    url: "{{ openshift4_version_map[openshift4_release_version].client_url }}"
    dest: /tmp/openshift-client-linux.tar.gz
    checksum: "{{ openshift4_version_map[openshift4_release_version].client_checksum }}" 
  retries: 5
  delay: 120
  register: download_client_result
  until: download_client_result.failed | bool == false

- name: 'Download the OpenShift installer'
  get_url:
    url: "{{ openshift4_version_map[openshift4_release_version].install_url }}"
    dest: /tmp/openshift-install-linux.tar.gz
    checksum: "{{ openshift4_version_map[openshift4_release_version].install_checksum }}"
  retries: 5
  delay: 120
  register: download_installer_result
  until: download_installer_result.failed | bool == false

- name: 'Extract the OpenShift client'
  unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/clis"
    remote_src: yes

- name: 'Extract the OpenShift installer'
  unarchive:
    src: /tmp/openshift-install-linux.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/clis"
    remote_src: yes
